<a href="https://colab.research.google.com/github/shivani5015/Machine-learning-Roadmap/blob/main/4.column_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ColumnTransformer Cheat Sheet

---

## Why Use ColumnTransformer?
Real-world datasets contain a mix of feature types (Numerical + Categorical). Applying different preprocessing steps manually and concatenating columns (`np.hstack`) makes code messy and increases the risk of **Data Leakage**.

**`ColumnTransformer`** applies specific transformations to specific column subsets in a single, clean pipeline.

---

## Key Parameters & Concepts

* **Single Pipeline:** Scales numerical features (e.g., `StandardScaler`) and encodes categorical features (e.g., `OneHotEncoder`) simultaneously.
* **`remainder='drop'`:** Drops all columns that were not explicitly transformed (default behavior).
* **`remainder='passthrough'`:** Keeps untransformed columns as they are without modifying them.

---

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#df.isnull().sum()

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['total_bill']),df['total_bill'],test_size=0.2)

In [ ]:
x_train.head()

      tip     sex smoker   day    time  size
191  4.19  Female    Yes  Thur   Lunch     2
212  9.00    Male     No   Sat  Dinner     4
157  3.75  Female     No   Sun  Dinner     4
152  2.74    Male     No   Sun  Dinner     3
138  2.00    Male    Yes  Thur   Lunch     2

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_num = si.fit_transform(x_train[['tip', 'size']])
X_train_num.shape

(195, 2)

In [ ]:
#ordinal encoding
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Female','Male'],['Yes','No'],['Sat','Sun','Thur','Fri']])
x_train_or=oe.fit_transform(x_train[['sex','smoker','day']])
x_test_or=oe.fit_transform(x_test[['sex','smoker','day']])
x_train_or.shape

(195, 3)

In [ ]:
#onehotencoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_time=ohe.fit_transform(x_train[['time']])
x_test_time=ohe.fit_transform(x_test[['time']])
x_train_time.shape

(195, 1)

In [ ]:
# Merging
x_train_merge = np.concatenate((X_train_num, x_train_or, x_train_time), axis=1)
x_train_merge.shape

(195, 6)

In [ ]:
#by column transformer

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['tip', 'size']),
    ('tnf2', OrdinalEncoder(categories=[['Female', 'Male'],['Yes','No'],['Sat','Sun','Thur','Fri']]), ['sex','smoker','day']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['time'])
], remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape

(195, 6)

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
encoded=pd.get_dummies(df,columns=['sex','smoker','time','size'],drop_first=True,dtype=int)
encoded.head()

,total_bill,tip,day,sex_Male,smoker_Yes,time_Lunch,size_2,size_3,size_4,size_5,size_6
0,16.99,1.01,Sun,0,0,0,1,0,0,0,0
1,10.34,1.66,Sun,1,0,0,0,1,0,0,0
2,21.01,3.50,Sun,1,0,0,0,1,0,0,0
3,23.68,3.31,Sun,1,0,0,1,0,0,0,0
4,24.59,3.61,Sun,0,0,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import OneHotEncoder
oe=OneHotEncoder(sparse_output=False,drop='first',dtype=np.int32)
ohe=oe.fit_transform(df[['day','time']])
ohe_a=pd.DataFrame(ohe)
ohe_a

     0  1  2  3
0    0  1  0  0
1    0  1  0  0
2    0  1  0  0
3    0  1  0  0
4    0  1  0  0
..  .. .. .. ..
239  1  0  0  0
240  1  0  0  0
241  1  0  0  0
242  1  0  0  0
243  0  0  1  0

[244 rows x 4 columns]

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
x=df.drop(columns=['tip'])
y=df['tip']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.impute import SimpleImputer
si=SimpleImputer()
x_train_num=si.fit_transform(x_train[['total_bill','size']])
x_train_num.shape

(195, 2)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Female','Male']])
x_train_sx=oe.fit_transform(x_train[['sex']])
x_test_sx=oe.fit_transform(x_test[['sex']])
x_train_sx.shape

(195, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_oe=ohe.fit_transform(x_train[['smoker','day','time']])
x_test_oe=ohe.fit_transform(x_test[['smoker','day','time']])
x_train_oe.shape

(195, 5)

In [ ]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transfromers=[
    ('tnsf1',SimpleImputer(),)
])