<a href="https://colab.research.google.com/github/shivani5015/Machine-learning-Roadmap/blob/main/6.intro_to_models_and_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#workflow of machine learning
#Data Ingestion-----> Data cleaning and preprocessing ---->select best Ml model
#according to data---->

#Model Training---->Model Prediction --->Model Perfromance Evaluation

In [ ]:
#Types of ml models
#1-- Supervised ml models ---->In this we will train our labelled data
#2--UnSupervised ML Models---> In this we will train our unlabelled data

In [ ]:
#supervised Models

In [ ]:
#If our Target Data is
#1--->Numerical -----LinearRegression , D.T.Regressor, R.FRegressor
#2---->Categorical---> LogisticRegression , D.T Classifier, R.F. Classifier, Naive bayes, SVM, KNN

In [ ]:
#1----LinearRegression Model

# Linear Regression Cheat Sheet

---

## What Is Linear Regression?
A **Supervised Machine Learning Algorithm** used to predict continuous numerical values (e.g., Salary, House Prices, Sales).

---

## Core Formulas

* **Simple Linear Regression (1 Feature):**
  $$y = mX + c$$
  * $y$: Target (Output to predict)
  * $X$: Feature (Input)
  * $m$: Slope / Weight
  * $c$: Intercept / Bias

* **Multiple Linear Regression ($n$ Features):**
  $$y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_n X_n$$

---

## Loss Function & Optimization

* **Loss Function (MSE):** Measures the average squared difference between actual ($y$) and predicted ($\hat{y}$) values.
  $$\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$
* **Goal:** Use **OLS** or **Gradient Descent** to adjust weights and minimize MSE to find the best-fit line.

---

## Performance Metrics

* **MAE (Mean Absolute Error):** Average absolute distance from true values. Easiest to interpret.
* **MSE (Mean Squared Error):** Heavily penalizes large errors by squaring them.
* **RMSE (Root Mean Squared Error):** $\sqrt{\text{MSE}}$ — restores errors back to the target variable's original unit.
* **$R^2$ Score:** Measures how much variance in $y$ is explained by the model ($1.0$ = Perfect fit).

---

## Key Assumption

1. **Linearity:** Relationship between features and target must be linear.
2. **No Multicollinearity:** Input features should not be highly correlated with each other (Check using **VIF**).
3. **Homoscedasticity:** Variance of residual errors must stay constant across predictions.
4. **Normality of Residuals:** Model errors should follow a normal distribution.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])
df['smoker']=le.fit_transform(df['smoker'])
df['region']=le.fit_transform(df['region'])

In [ ]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
#y_pred

In [ ]:
y_test

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

0.7833463107364539