<a href="https://colab.research.google.com/github/shivani5015/Machine-learning-Roadmap/blob/main/Decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Decision Tree Model -------CART(Classification and Regression TRee)
#when data is numerical--branch individual output average----final output
#whe data is Categorical---branch individual output(100 covid patients)---70 output(yes),30 output (no)--final output 70 yes

#  Quick Cheat-Sheet: Decision Tree (Classifier & Regressor)

##  Main Goal
Decision Tree ek non-parametric **Supervised Learning Algorithm** hai jo data ko flowchart-like tree structure mein split karke decisions leta hai.
* **Classifier:** Categorical target variables predict karta hai (e.g., Yes/No).
* **Regressor:** Continuous numerical values predict karta hai (e.g., House Price).

---

##  How Decision Trees Split Data?

### 1. Decision Tree Classifier (Splitting Criteria)

#### A. Gini Impurity (Default in Scikit-Learn)
Purity ki measurement ($0$ matbal 100% pure node). Fast to compute.
$$\text{Gini} = 1 - \sum_{i=1}^{k} p_i^2$$

#### B. Entropy & Information Gain (IG)
Disorder / Uncertainty ki measurement.
$$\text{Entropy}(S) = -\sum_{i=1}^{k} p_i \log_2(p_i)$$
$$\text{Information Gain} = \text{Entropy}(Parent) - \text{Weighted Average Entropy}(Children)$$
* Node us feature par split hota hai jiska **Information Gain Highest** ho.

---

### 2. Decision Tree Regressor (Splitting Criterion)

* **Variance Reduction / MSE:** Numerical target ke liye algorithm variance ya Mean Squared Error (MSE) calculate karta hai.
$$\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \bar{y})^2$$
* Leaf node ka final prediction: Us node mein aane wale saare data points ka **Average (Mean)**.

---

##  Overfitting & Hyperparameter Tuning (Pruning)

Decision Trees bohot jaldi **Overfit** ho jate hain (Training Accuracy 100% ho jati hai lekin Testing par fail ho jate hain). Isse bachne ke liye Hyperparameters adjust karte hain:

1. **`max_depth`:** Tree ki maximum height/depth limit karna.
2. **`min_samples_split`:** Split karne ke liye minimum kitne samples hone chahiye.
3. **`min_samples_leaf`:** Leaf node par kam se kam kitne samples bachne chahiye.
4. **`max_features`:** Every split par kitne random features consider karne hain.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])
df['smoker']=le.fit_transform(df['smoker'])
df['region']=le.fit_transform(df['region'])

In [ ]:
df.head(2)

   age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
y_pred=dt.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7222287396961817

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads.csv")
df.head(2)

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [ ]:
df['Gender']=le.fit_transform(df['Gender'])

In [ ]:
df.head(2)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0

In [ ]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dc=DecisionTreeClassifier()
dc.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dc.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8875

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['has_covid']=le.fit_transform(df['has_covid'])

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
de=DecisionTreeClassifier()
de.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=de.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5